In [3]:
import torch

In [12]:
t = torch.tensor([1,2,3])


tensor([1, 2, 3])

In [20]:
import torch
import numpy as np

In [ ]:
t = torch.Tensor()
type(t)
print(t.dtype)
print(t.device)
print(t.layout)

device = torch.device("cuda:0")
device

In [38]:
#numpy like operations
torch.eye(4)
torch.zeros(4,4)
torch.ones(4,4)
torch.rand(3,3)

tensor([[0.9500, 0.7322, 0.0321],
        [0.0066, 0.0442, 0.0060],
        [0.8717, 0.6812, 0.9150]])

In [48]:
#some try outs with differnt functions with arrays
data = np.array([1,2,3])

t1 = torch.Tensor(data) # constructer, uses default type
torch.get_default_dtype()

#factories use dtype infered from data
t2 = torch.tensor(data) # factory
t3 = torch.as_tensor(data) # factory
t4 = torch.from_numpy(data) # factory

print(t1.dtype) # copy input
print(t2.dtype) # copy inputs --> best option
print(t3.dtype) # share inputs --> 
print(t4.dtype) # share inputs

#specify it manually
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

torch.float32
torch.int32
torch.int32
torch.int32


tensor([1., 2., 3.], dtype=torch.float64)

In [52]:
# reshaping operations:: very important

# element wise operations
# 


torch.Size([3, 4])

In [57]:
t = torch.tensor([[1,1,1,1],[2,2,2,2], [3,3,3,3]], dtype=torch.float32)
t.size()
t.shape

len(t.shape)
torch.tensor(t.shape).prod()
t.numel() # number of elements

# flatten --> 1d array containing all scalars




In [62]:
def flatten(t):
    t = t.reshape(1,-1)
    t - t.squeeze()
    return t

flatten(t)
#alternative for flatten function
t.reshape(t.numel(), 1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])